version: "3.9"
services:
  db:
    container_name: ${CONTAINER_NAME}_db
    build: ./backend/docker/database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DBNAME=${POSTGRES_DBNAME}
    volumes:
      - ./backend/docker/database/data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-h", "cw_db"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    container_name: ${CONTAINER_NAME}_api
    build: ./backend/docker/api
    command: sh -c "./run_api.sh"
    volumes:
      - ./backend/api/:/app/api
      - ./backend/run.py:/app/run.py
      - ./.env:/.env
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-I", "--fail", "http://127.0.0.1:80/api/status"]
      interval: 30s
      timeout: 3s
      retries: 5

  nginx:
    container_name: ${CONTAINER_NAME}_nginx
    build: ./frontend
    restart: always
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
